dist: trusty
language: node_js
node_js:
- stable
notifications:
  email:
    recipients:
    - julia.z@chello.at
    on_success: never        # default: change
    on_failure: always       # default: always
script:
  - npm run coverage
after_success:
  - npm run publish-coverage
branches:
  only: development
